### ISSUE TITLE
Is it possible to get original data in the sample Sfcc LWC app, .i.e my site data( eg: funi ), i have all the details like organizationid, client id and so on ,but when i use my details also the app is always showing dummy data of clothes, in the sample app of LWC, how can i get my original data

### ISSUE THREAD

**Issue by saivenkatesh48** [SalesforceCommerceCloud/commerce-sdk#253]

**Comment by jbegleiter-sf** [comment]
Hey @saivenkatesh48 ,

This sounds like a sample app configuration issue. Can you privately send me the configuration information you are using (as it contains potentially sensitive information), as well as a place to review the running application?

Cheers,
Josh

**Comment by saivenkatesh48** [comment]
where can i share you the config info privately,i am unable to see
![heroImage](https://user-images.githubusercontent.com/4180281/88574018-42d5cd80-d05f-11ea-9e4d-ac099537c821.jpg), but i want my details andone more thing is when click on any category like Men or etc, then error is comming as **Authorization Token has expired undefined**

**Comment by jbegleiter-sf** [comment]
@saivenkatesh48 you can shoot me an email ( jbegleiter AT salesforce DOT com ), and the authorization token issue was fixed in latest master of sample app (released Thursday last week).

**Comment by saivenkatesh48** [comment]
can i send the api.js file which contain my details,i am just mention all the items in this js file.
i have downloaded the sample app yesterday only, but still getting the same issue,

**Comment by jbegleiter-sf** [comment]
@saivenkatesh48 if you have the most recent sample app I think this is likely a configuration issue, as well. Feel free to send over the api.js file.

**Comment by saivenkatesh48** [comment]
sure, thanks.

**Comment by saivenkatesh48** [comment]
i have shared the email, please go through it and help me to solve the issue,i am just configuring product detail url, or can i need to call login url before shopper product api?

**Comment by saivenkatesh48** [comment]
The process what i did is:
1.download the sample app with recent release.
2.yarn install  all node modules in the app.
3.yarn install node module in @sffc-bff,@Sfcc-core,Storefront-lwc
4.copy api.example .js  file and renameit to app.js
5.In app.js i have given my credentail details
6.after that run the command in terminal like yarn build, yarn start:dev
these are the steps i did, did i miss any let me know.

**Comment by saivenkatesh48** [comment]
**one more important question for me is**
can i run this sample as Mobile app, i have read in the it follows PWA(Progress web app) for iOS, can i run the same app in android also or can i only able to run in Ios?

**Comment by jbegleiter-sf** [comment]
The sample app is responsive but it is a web app. You could run it in a webview and that *should* work, but I haven't tried it, and the JS engine may not fully support the features (no guarantees).

I have found some issues in your configuration and am investigating the correct values for you.

**Comment by saivenkatesh48** [comment]
thanks,can you please investigate and let me know.

**Comment by saivenkatesh48** [comment]
one more question, what is the way, if i want to develop mobile app using the Commerce SDK,
my requirement is , i need mobile app which uses this SDK.

**Comment by jbegleiter-sf** [comment]
@saivenkatesh48 to implement this for mobile we recommend introducing an "experience layer" that utilizes the SDK (in the case of the sample app it uses a BFF), as opposed to using the SDK directly in the client.

**Comment by saivenkatesh48** [comment]
HI, even after using newly generateed shortcode i am getting this issue, i have sent mail to you regarding this.


storefront-lwc: Authorization Token has expired Response {
storefront-lwc:   size: 0,
storefront-lwc:   timeout: 0,
storefront-lwc:   [Symbol(Body internals)]: {
storefront-lwc:     body: Minipass {
storefront-lwc:       _events: [Object: null prototype],
storefront-lwc:       _eventsCount: 5,
storefront-lwc:       _maxListeners: undefined,
storefront-lwc:       pipes: [Yallist],
storefront-lwc:       buffer: [Yallist],
storefront-lwc:       writable: true,
storefront-lwc:       readable: true,
storefront-lwc:       [Symbol(kCapture)]: false,
storefront-lwc:       [Symbol(flowing)]: false,
storefront-lwc:       [Symbol(paused)]: false,
storefront-lwc:       [Symbol(objectMode)]: false,
storefront-lwc:       [Symbol(encoding)]: null,
storefront-lwc:       [Symbol(decoder)]: null,
storefront-lwc:       [Symbol(EOF)]: false,
storefront-lwc:       [Symbol(emittedEnd)]: false,
storefront-lwc:       [Symbol(emittingEnd)]: false,
storefront-lwc:       [Symbol(closed)]: false,
storefront-lwc:       [Symbol(bufferLength)]: 956,
storefront-lwc:       [Symbol(destroyed)]: false
storefront-lwc:     },
storefront-lwc:     disturbed: false,
storefront-lwc:     error: null
storefront-lwc:   },
storefront-lwc:   [Symbol(Response internals)]: {
storefront-lwc:     url: 'https://z61e3rz8.api.commercecloud.salesforce.com/customer/shopper-customers/v1/organizations/f_ecom_bdgc_bdgc_s05/customers/actions/login?clientId=5d5667fb-1401-43f0-8277-9df51aaf6ea8&siteId=funimation-us',
storefront-lwc:     status: 530,
storefront-lwc:     statusText: undefined,
storefront-lwc:     headers: Headers { [Symbol(map)]: [Object: null prototype] },
storefront-lwc:     counter: 0,
storefront-lwc:     trailer: Promise { <pending> }
storefront-lwc:   }
storefront-lwc: }
storefront-lwc: Error in requestWithTokenRefresh() ResponseError: 530 undefined  
storefront-lwc:     at Object.<anonymous> (D:\sfcc_demoapp\sfcc-sample\sfcc-sample\node_modules\commerce-sdk\dist\helpers.js:36:13)
storefront-lwc:     at Generator.next (<anonymous>)
storefront-lwc:     at fulfilled (D:\sfcc_demoapp\sfcc-sample\sfcc-sample\node_modules\tslib\tslib.js:110:62)
storefront-lwc:     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
storefront-lwc:   response: Response {
storefront-lwc:     size: 0,
storefront-lwc:     timeout: 0,
storefront-lwc:     [Symbol(Body internals)]: { body: [Minipass], disturbed: false, error: null },
storefront-lwc:     [Symbol(Response internals)]: {
storefront-lwc:       url: 'https://z61e3rz8.api.commercecloud.salesforce.com/customer/shopper-customers/v1/organizations/f_ecom_bdgc_bdgc_s05/customers/actions/login?clientId=5d5667fb-1401-43f0-8277-9df51aaf6ea8&siteId=funimation-us',
storefront-lwc:       status: 530,
storefront-lwc:       statusText: undefined,
storefront-lwc:       headers: [Headers],
storefront-lwc:       counter: 0,
storefront-lwc:       trailer: [Promise]
storefront-lwc:     }
storefront-lwc:   }

**Comment by saivenkatesh48** [comment]
Hi Jose,Even i run y**arn start:dev** command also, i am getting the above mentioned issue.

**Comment by jbegleiter-sf** [comment]
Taking this to an offline thread.
